In [18]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [19]:
df=pd.read_csv("WeatherAUS.csv",usecols=['MinTemp', 'MaxTemp', 'Temp9am', 'Temp3pm', 'Humidity9am', 'Humidity3pm','Pressure9am','Pressure3pm','RainTomorrow'])

In [20]:
df.head()

,MinTemp,MaxTemp,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainTomorrow
0,13.4,22.9,71.0,22.0,1007.7,1007.1,16.9,21.8,No
1,7.4,25.1,44.0,25.0,1010.6,1007.8,17.2,24.3,No
2,12.9,25.7,38.0,30.0,1007.6,1008.7,21.0,23.2,No
3,9.2,28.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No
4,17.5,32.3,82.0,33.0,1010.8,1006.0,17.8,29.7,No

In [21]:
df.isnull().mean()*100

MinTemp          1.020899
MaxTemp          0.866905
Humidity9am      1.824557
Humidity3pm      3.098446
Pressure9am     10.356799
Pressure3pm     10.331363
Temp9am          1.214767
Temp3pm          2.481094
RainTomorrow     2.245978
dtype: float64

In [22]:
df = df.dropna(subset=['RainTomorrow'])

In [23]:
X=df.drop(columns=['RainTomorrow'])
y=df['RainTomorrow']

In [24]:
X.head()

,MinTemp,MaxTemp,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm
0,13.4,22.9,71.0,22.0,1007.7,1007.1,16.9,21.8
1,7.4,25.1,44.0,25.0,1010.6,1007.8,17.2,24.3
2,12.9,25.7,38.0,30.0,1007.6,1008.7,21.0,23.2
3,9.2,28.0,45.0,16.0,1017.6,1012.8,18.1,26.5
4,17.5,32.3,82.0,33.0,1010.8,1006.0,17.8,29.7

In [25]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [26]:
x_train.head()

,MinTemp,MaxTemp,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm
18401,15.1,23.9,38.0,68.0,1001.9,1002.4,19.8,14.3
127797,9.7,14.2,91.0,56.0,1008.2,1007.7,11.1,13.4
40012,13.2,25.4,79.0,63.0,1025.2,1021.5,21.2,24.0
130914,7.6,14.8,52.0,45.0,1004.6,1001.4,11.1,12.9
41742,12.9,22.2,69.0,52.0,1023.0,1021.2,18.8,20.6

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

In [31]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=x_train.columns)

In [29]:

knn=KNNImputer(n_neighbors=10)
x_train_trf=knn.fit_transform(X_train_scaled)
x_test_trf=knn.transform(X_test_scaled)

In [32]:
pd.DataFrame(x_train_trf,columns=X_train_scaled.columns)

,MinTemp,MaxTemp,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm
0,0.456958,0.095135,-1.616995,0.794900,-2.214972,-1.826360,0.433921,-1.063734
1,-0.386956,-1.267578,1.163261,0.217957,-1.329062,-1.073546,-0.906280,-1.193423
2,0.160025,0.305864,0.533769,0.554507,1.061490,0.886612,0.649586,0.334023
3,-0.715144,-1.183287,-0.882588,-0.310908,-1.835296,-1.968400,-0.906280,-1.265472
4,0.113141,-0.143691,0.009192,0.025642,0.752125,0.843999,0.279875,-0.155913
...,...,...,...,...,...,...,...,...
113749,-0.496352,-0.607295,-0.111460,0.376616,-0.021289,0.346858,-0.182263,-0.588209
113750,0.144397,-0.466809,1.110803,0.169878,0.063083,0.417878,-0.243882,-0.372061
113751,-0.215047,0.319912,-1.459622,-1.464795,-0.274407,-0.377548,-0.259286,0.204334
113752,-0.136907,-0.256080,0.323938,1.323765,0.326044,0.081243,-0.182263,-0.861996
113753,-0.293187,0.685175,-0.935045,-1.128244,0.027928,-0.059377,0.418517,0.723089

In [33]:
lr=LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred=lr.predict(x_test_trf)
accuracy_score(y_test,y_pred)

0.8278772108723935

In [38]:
#comparision with simple imputer
si=SimpleImputer()
x_train_trf2=si.fit_transform(x_train)
x_test_trf2=si.transform(x_test)

In [42]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
x_train_trf2_scaled=s.fit_transform(x_train_trf2)
x_test_trf2_scaled=s.transform(x_test_trf2)

In [43]:
lr=LogisticRegression()
lr.fit(x_train_trf2_scaled,y_train)
y_pred2=lr.predict(x_test_trf2_scaled)
accuracy_score(y_test,y_pred2)

0.8260135729104399